version: "3.3"
services:
  ringpi-doorbell:
    build: .
    network_mode: host # Required for nest mini connectivity
    restart: unless-stopped
    environment:
      RING_REFRESH_TOKEN: $RING_REFRESH_TOKEN
      RING_CAMERA_NAME: $RING_CAMERA_NAME
      NEST_MINI_HOST: $NEST_MINI_HOST
      CHIME_URL: $CHIME_URL
